version: '2'

services:
  server:
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    environment:
      - PARSE_SERVER_DATABASE_URI=mongodb://mongodb:27017/parse-server-boilerplate
  mongodb:
    image: mongo:3.2.6
    ports:
      - 27017:27017
