version: '2'

services:
  server:
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    network_mode: 'host'
  mongodb:
    image: mongo:3.2.6
    ports:
      - 27017:27017
    network_mode: 'host'
